name: Bug
description: Report a bug here
title: "[Bug] Replace this with your title"
labels: bug
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    options:
    - label: I have searched the existing issues
      required: true

- type: markdown
  attributes:
    value: "## Device Info"

- type: input
  attributes:
    label: iOS/iPadOS version
    placeholder: iOS 17.5.1
  validations:
    required: true

- type: input
  attributes:
    label: Device model
    placeholder: iPhone 15 Pro Max
  validations:
    required: true

- type: input
  attributes:
    label: Sideload method
    placeholder: AltStore, Sideloadly, TrollStore, Signulous, deb, ...
  validations:
    required: true

- type: input
  attributes:
    label: Tweak version
    placeholder: YTLitePlus - v19.xx.x-4.0.1
    description: "**latest or newest is NOT a version number!**"
  validations:
    required: true

- type: dropdown
  attributes:
    label: Do you use YouTube Premium?
    options:
      - ❌ No, I don't use YouTube Premium
      - ✅ Yes, I do use YouTube Premium
  validations:
    required: true

- type: dropdown
  attributes:
    label: Are you using the newest version of YTLitePlus?
    description: Update to the [latest version](https://github.com/YTLitePlus/YTLitePlus/releases) to see if it fixes your issue
    options:
      - ✅ Yes, I'm using the latest version
      - ❌ No, I'll explain at the end
  validations:
    required: true

- type: dropdown
  attributes:
    label: Does the issue happen with the official YouTube from AppStore?
    options:
      - ❌ No, I can't reproduce this issue in the official YouTube from AppStore 
      - ✅ Yes, I can reproduce this issue in the official YouTube from AppStore 
  validations:
    required: true

- type: dropdown
  attributes:
    label: Method used to build the iPA
    options:
      - buildapp.yml (GitHub Actions)
      - build.sh (Shell script)
      - Downloaded from third party
  validations:
    required: true

- type: markdown
  attributes:
    value: "## Description"

- type: textarea
  attributes:
    label: Describe the bug
    description: Please attach videos or screenshots if possible
  validations:
    required: true

- type: textarea
  attributes:
    label: Steps to reproduce the issue
    description: Please attach videos or screenshots if possible
    value: |
        1. 
        2. 
        3. 
  validations:
    required: true

- type: textarea
  id: logs
  attributes:
    label: Crash log (if the app crashes)
    description: It can be found in Settings App > Privacy > Analytics & Improvements > Analytics Data > Youtube-xxx-xxx.ips
    render: shell

- type: textarea
  attributes:
    label: Additional context
  validations:
    required: false
